# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres-test
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5342:5342
