kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: awx-db
  labels:
    app: awx
    role: db-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: default